apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: guilhermemarques1/sql-k8s:1.0
          args:
            - "--ignore-db-dir=lost+found"
          imagePullPolicy: Always
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: senha123
            - name: MYSQL_DATABASE
              value: meubanco
          ports:
            - containerPort: 3306
              name: mysql

          volumeMounts:
            - name: mysql-dados
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-dados
          persistentVolumeClaim:
            claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app-php
  labels:
    app: meu-app-php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: meu-app-php
  template:
    metadata:
      labels:
        app: meu-app-php
    spec:
      containers:
        - image: guilhermemarques1/php-k8s:4.0
          imagePullPolicy: Always
          name: meu-app-php
          ports:
            - containerPort: 80
