apiVersion: v1
kind: Service
metadata:
  name: meu-app-php
spec:
  selector:
    app: meu-app-php
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
